version: '3.8'
services:
  mssql:
    build:
      context: ./
      dockerfile: Dockerfile
    #logging:
    #  driver: none
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/opt/mssql/data
    ports:
      - "7000:1433"