version: '3.8'
services:
  pgdb:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: DataPlatform01
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    logging:
      driver: none
    #restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 7000:5432